package com.foodie.request;

import jakarta.validation.constraints.*;
import lombok.Data;

import java.util.List;

@Data
public class MenuItemRequest {
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must be less than 100 characters")
    private String name;

    @Size(max = 500, message = "Description must be less than 500 characters")
    private String description;

    @Positive(message = "Price must be positive")
    private double price;

    private boolean available;

    private boolean vegetarian;

    private List<String> images;

    @NotNull(message = "Category ID is required")
    private Long categoryId;

    private String templateType;

    private List<Long> ingredientIds;

    // Getters and setters generated by Lombok
}