package com.foodie.request;

import jakarta.validation.constraints.*;
import lombok.Data;

import java.util.List;

@Data
public class PreDefineMenuItemRequest {
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must be less than 100 characters")
    private String name;

    @Size(max = 500, message = "Description must be less than 500 characters")
    private String description;

    @Positive(message = "Price must be positive")
    private double price;

    private boolean vegetarian;

    @NotNull(message = "Images are required")
    private List<String> image;

    private String templateType;

    @NotNull(message = "Menu category ID is required")
    private Long menuCategoryId;

    private List<Long> ingredientId;

    // Getters and setters generated by Lombok
}